server:
  shutdown: graceful
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:data
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: validate
        show_sql: false
        auto_quote_keyword: true
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher